#### Feed foreward neural network breakup creation


In [1]:
!pip install torch

     ---------------------------------------- 0.0/172.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/172.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/172.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/172.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/172.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/172.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/172.3 MB ? eta -:--:--
     -------------------------------------- 0.0/172.3 MB 103.4 kB/s eta 0:27:46
     -------------------------------------- 0.0/172.3 MB 103.4 kB/s eta 0:27:46
     -------------------------------------- 0.0/172.3 MB 103.4 kB/s eta 0:27:46
     -------------------------------------- 0.0/172.3 MB 103.4 kB/s eta 0:27:46
     -------------------------------------- 0.1/172.3 MB 105.6 kB/s eta 0:27:12
     -------------------------------------- 0.1/172.3 MB 115.5 kB/s eta 0:24:52
     ----

In [5]:
!pip install pingouin
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split  #split the test set 
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score

from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import PolynomialFeatures

from sklearn.linear_model import RidgeCV
from sklearn.linear_model import LassoCV
from sklearn.linear_model import ElasticNetCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import PolynomialFeatures

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import statsmodels.api as sm

import pingouin as pg



In [37]:
import numpy as np
from sklearn import datasets
#
import numpy as np

# Set the random seed for reproducibility (optional)
np.random.seed(42)

# Generate a random matrix of size 200x4 with noise 0.2
X = np.random.normal(loc=0, scale=0.2, size=(200, 4))


In [38]:
X

array([[ 0.09934283, -0.02765286,  0.12953771,  0.30460597],
       [-0.04683067, -0.04682739,  0.31584256,  0.15348695],
       [-0.09389488,  0.10851201, -0.09268354, -0.09314595],
       [ 0.04839245, -0.38265605, -0.34498357, -0.11245751],
       [-0.20256622,  0.06284947, -0.18160482, -0.28246074],
       [ 0.29312975, -0.04515526,  0.01350564, -0.28494964],
       [-0.10887654,  0.02218452, -0.23019872,  0.0751396 ],
       [-0.12012774, -0.05833875, -0.12034132,  0.37045564],
       [-0.00269944, -0.21154219,  0.16450898, -0.24416873],
       [ 0.04177272, -0.39193402, -0.26563721,  0.03937225],
       [ 0.14769332,  0.03427366, -0.02312966, -0.06022074],
       [-0.2957044 , -0.14396884, -0.09212775,  0.21142445],
       [ 0.06872366, -0.35260803,  0.06481679, -0.07701646],
       [-0.1353844 ,  0.12233526,  0.2061999 ,  0.18625602],
       [-0.1678435 , -0.06184248,  0.06625269,  0.19510903],
       [-0.09583485, -0.0371318 , -0.22126699, -0.23924132],
       [ 0.16250516,  0.

In [39]:
X.shape

(200, 4)

In [13]:
#
# Neural network architecture
# No of nodes in input layer = 4
# No of nodes in output layer = 3
# No of nodes in the hidden layer = 6
#
input_dim = 4 # input layer dimensionality
output_dim = 3 # output layer dimensionality
hidden_dim = 6 # hidden layer dimensionality
#
# Weights and bias element for layer 1
# These weights are applied for calculating
# weighted sum arriving at neurons in 1st hidden layer
#
W1 = np.random.randn(input_dim, hidden_dim)
b1 = np.zeros((1, hidden_dim))
#

In [14]:
W1 

array([[ 0.43428686,  0.55889843,  0.84272357,  1.3929767 ,  0.36755118,
        -1.89916811],
       [-1.53190491,  0.07600218, -0.52731942, -0.15469037, -0.29927236,
         0.70850768],
       [-0.57982513,  1.68992749, -0.42659837, -0.19692692, -1.86805984,
        -1.30729405],
       [-0.44055929, -0.99882534, -1.04856139,  0.57189115,  0.1502691 ,
         0.78847387]])

In [15]:
W1.shape

(4, 6)

In [16]:
b1

array([[0., 0., 0., 0., 0., 0.]])

In [17]:
b1.shape

(1, 6)

In [18]:
# Weights and bias element for layer 2
# These weights are applied for calculating
# weighted sum arriving at neurons in 2nd hidden layer
#
W2 = np.random.randn(hidden_dim, hidden_dim)
b2 = np.zeros((1, hidden_dim))

In [19]:
W2

array([[ 2.10187965, -0.65117694,  0.33736087, -1.62458195, -0.28856812,
        -0.35468003],
       [-0.92956752,  0.03245805, -0.3164847 ,  1.06605778,  0.46385883,
        -1.44927076],
       [ 0.63446386,  1.43692767, -1.21142064,  0.2901355 , -1.60419962,
         1.01505813],
       [ 0.46966219,  0.42264642, -1.68823281, -1.69480065,  0.1295877 ,
         0.25465471],
       [-0.07388109, -0.46600766,  1.88017278,  0.98423108,  1.42654119,
        -1.15284674],
       [ 1.45556787,  0.3807047 , -0.20547668,  0.85911458, -1.07408218,
         0.74078008]])

In [20]:
W2.shape

(6, 6)

In [21]:
b2

array([[0., 0., 0., 0., 0., 0.]])

In [22]:
b2.shape

(1, 6)

In [24]:


# Weights and bias element for layer 2
# These weights are applied for calculating
# weighted sum arriving at in the final / output layer
#
W3 = np.random.randn(hidden_dim, output_dim)
b3 = np.zeros((1, output_dim))

In [25]:
W3.shape

(6, 3)

In [26]:
b3.shape

(1, 3)

In [40]:
# Forward propagation of input signals
# to 6 neurons in first hidden layer
# activation is calculated based tanh function
#
temp=X[0].dot(W1)
temp.shape

(6,)

In [42]:
z1 = temp + b1
z1.shape

(1, 6)

In [44]:
a1 = np.tanh(z1)
a1.shape

(1, 6)

In [47]:
#
# Forward propagation of activation signals from first hidden layer
# to 6 neurons in second hidden layer
# activation is calculated based tanh function
#
z2 = a1.dot(W2) + b2
a2 = np.tanh(z2)
z2.shape

(1, 6)

In [48]:
a2.shape

(1, 6)

In [49]:
#
# Forward propagation of activation signals from second hidden layer
# to 3 neurons in output layer
#
z3 = a2.dot(W3) + b3
z3.shape

(1, 3)

In [51]:
# Probability is calculated as an output
# of softmax function
#
probs = np.exp(z3) / np.sum(np.exp(z3), axis=1, keepdims=True)
probs

array([[0.073414  , 0.88190347, 0.04468252]])

In [56]:
import numpy as np

# Declare a 200x4 matrix filled with zeros
new_matrix = np.zeros((200, 4))

In [67]:
matrix1 = np.empty((200, output_dim))


In [69]:
for i in range (0,200):
    temp=X[i].dot(W1)
    temp.shape
    z1 = temp + b1
    z1.shape
    a1 = np.tanh(z1)
    z2 = a1.dot(W2) + b2
    a2 = np.tanh(z2)
    z3 = a2.dot(W3) + b3
    probs = np.exp(z3) / np.sum(np.exp(z3), axis=1, keepdims=True)
    #print(probs)
    matrix1[i]= probs
print (matrix1)

[[0.073414   0.88190347 0.04468252]
 [0.29839492 0.5668877  0.13471738]
 [0.32182152 0.03164063 0.64653785]
 [0.04311873 0.87682438 0.08005689]
 [0.24898772 0.01211209 0.73890019]
 [0.17862705 0.78271028 0.03866268]
 [0.19201666 0.07417963 0.7338037 ]
 [0.13472665 0.3517229  0.51355045]
 [0.20514644 0.72186362 0.07298995]
 [0.02982565 0.91371641 0.05645794]
 [0.26987184 0.59362217 0.13650599]
 [0.1455878  0.11506288 0.73934933]
 [0.05257797 0.92199746 0.02542457]
 [0.43314026 0.08378113 0.48307862]
 [0.24347295 0.21830766 0.53821939]
 [0.27467227 0.05688417 0.66844355]
 [0.41248954 0.26143495 0.32607551]
 [0.04393834 0.91752593 0.03853573]
 [0.17138037 0.01710309 0.81151654]
 [0.52674941 0.23242348 0.24082712]
 [0.63883732 0.11416806 0.24699462]
 [0.34825795 0.29579501 0.35594705]
 [0.29461421 0.08825653 0.61712926]
 [0.3673825  0.05461585 0.57800165]
 [0.39783739 0.32339488 0.27876773]
 [0.23075629 0.03024773 0.73899597]
 [0.60915687 0.1697436  0.22109952]
 [0.16111107 0.3844375  0.45

![The above is the code for this feed foreward neural network with 4 nodes as input in the input layer and 3 node as the output layer, the dataset is taken at random with 200 datapoints](FFNN.jpg)
